spring:
  h2:
    console:
      enabled: true
  datasource:
    #url: jdbc:h2:mem:test;MODE=MySQL
    #url: jdbc:h2:~/test
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create